oneforall/urls.py
from django.contrib import admin
from django.urls import include, path

from searcher import views
urlpatterns = [
    path('', views.home, name='home_url'),
    path('searcher/', include('searcher.urls')),
    path('admin/', admin.site.urls),
]

searcher/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
app_name = 'searcher'

urlpatterns = [
    path('us/', views.us,name='us_url'),
    path('result/',views.result,name='result_url'),
    path('analytics/', views.analytics,name='analytics_url')
]

searcher/models.py
from django.db import models

# Create your models here.
class Info(models.Model):
    ten = models.CharField(verbose_name='Tên sản phẩm',max_length=265)
    gia_goc = models.FloatField(verbose_name='Giá gốc',default=0)
    gia_sale = models.FloatField(verbose_name='Giá sale', default=0)
    sale_rate= models.CharField(verbose_name='Phần trăm sale',max_length=10)
    con_hang = models.CharField(verbose_name='Còn hàng',max_length=100, null=True)
    luot_danh_gia = models.IntegerField(verbose_name='Số đánh giá', default=0)
    sao = models.IntegerField(verbose_name='Số sao', default=0)
    link_sp = models.URLField(verbose_name='Link sản phẩm', max_length=265, null=True)
    anh_sp = models.ImageField(verbose_name='Ảnh sản phẩm', upload_to = 'media_anh', blank=True)

    def __str__(self):
        return self.ten

searcher/views.py
from django.shortcuts import render
from searcher.models import Info
# Create your views here.
def home(request):
    return render(request, 'searcher/home.html')

def us(request):
    return render(request, 'searcher/us.html')

def analytics(request):
    return render(request, 'searcher/analytics.html')

def recommend(request):
    return render(request, 'searcher/recommend.html')

def result(request):
    res_sale_rate = Info.objects.order_by('sale_rate')
    sale_rate_dict = {'top_sale': res_sale_rate}
    return render(request, 'searcher/result.html', context = sale_rate_dict)

templates/searcher/analytics.html
{% extends "searcher/base.html" %}
{% load static %}
<div class="container">
  <div class="jumbotron">
     <img src="{% static "images/dashboard.png" %}" alt="A picture of some random chart">
  </div>

</div>
{% block body_block%}
{% endblock %}

templates/searcher/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <!-- NAVBAR -->
    <nav class = "navbar navbar-default navbar-static-top navbar-inverse">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'home_url' %}"><b>RADER</b></a></li>
          <li><a class="navbar-link" href="{% url 'searcher:analytics_url'%}">SALE ANALYTICS</a></li>
          <li><a class="navbar-link" href="{% url 'searcher:us_url'%}">ABOUT US</a></li>
        </ul>
      </div>
    </nav>


    {% block body_block %}
    <!-- INHERIT HERE -->
    {% endblock %}


  </body>
</html>

templates/searcher/home.html
{% extends "searcher/base.html" %}

{% block body_block%}
<div class="container">
  <div class="jumbotron">
    <h1>WELCOME TO RADER</h1>
    <h2>FIND WHAT YOU NEED WITH A CLICK</h2>
    <div class="container">
      <input type="text" name="" value="" placeholder="Type your item here">
      <button type="button" class="btn btn-danger"><a href="{% url 'searcher:result_url' %}">Search</a></button>
    </div>
  </div>
</div>
{% endblock %}

templates/searcher/result.html
{% extends "searcher/base.html" %}

{% block body_block%}
<div class="container">
  <div class="jumbotron">
    <h2>Your results goes here</h1>
    <table>
      <thead>
        <th>Tên sản phẩm</th>
        <th>Giá gốc</th>
        <th>Giá sale</th>
        <th>Phần trăm sale</th>
        <th>Số đánh giá</th>
        <th>Số sao</th>
        <th>Tình trạng sản phẩm</th>
        <th>Link sản phẩm</th>
        <th>Ảnh sản phẩm</th>


      </thead>
      {% for item in top_sale %}
      <tr>
        <td>{{item.ten}}</td>
        <td>{{item.gia_goc}}</td>
        <td>{{item.gia_sale}}</td>
        <td>{{item.sale_rate}}</td>
        <td>{{item.con_hang}}</td>
        <td>{{item.luot_danh_gia}}</td>
        <td>{{item.sao}}</td>
        <td>{{item.link_sp}}</td>
        <td>{{item.anh_sp}}</td>
      </tr>
      {% endfor %}
    </table>

  </div>

</div>
{% endblock %}

templates/searcher/us.html
{% extends "searcher/base.html" %}

{% block body_block%}
<body>
  <div class="container">
    <div class="jumbotron">
      <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h3>
      <h4>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h4>
    </div>
  </div>

{% endblock %}